---

- name: Percona repo key
  apt_key: url=http://www.percona.com/downloads/RPM-GPG-KEY-percona state=present

- name: Percona repo
  apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present

- name: Percona src repo
  apt_repository: repo='deb-src http://repo.percona.com/apt trusty main' state=present

- name: install packages
  action: apt pkg={{ item }} state=installed update_cache=yes
  with_items:
     - percona-server-client-5.6
     - percona-server-common-5.6
     - percona-server-server-5.6
     - percona-toolkit
     - percona-xtrabackup-21
  environment:
     DEBIAN_FRONTEND: noninteractive
